### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by randymorris** [cuspymd/tramp-term.el#12]
I have let this project go for far too long and I just don't have time to keep up with it these days.  Please let me know if you'd like to take over maintenance.  Thus far it has been a very low maintenance project.  Unfortunately I haven't really used this solution for years so I don't know how the inner workings in newer versions of Emacs may have affected tramp-term over time.

**Comment by cuspymd** [comment]
Hi, I'm interest in maintaining this package. Could you take over it? 
I haven't tried to maintain the Melpa package yet. I think this package will be a good opportunity.

**Comment by randymorris** [comment]
Sorry for the slow response.  If you're still interested I'd be happy to pass this on to you.  Please let me know and I'll figure out what I need to do to pass the torch.

**Comment by cuspymd** [comment]
@randymorris Thanks for your reply. Yes. I'm still interested.

**Comment by randymorris** [comment]
I've initiated the transfer.  I'm not sure how GitHub handles the URL, if it changes you'll need to make a pull request on the melpa project to update the URL.

Thanks for taking this over.  Hopefully you'll have time to look into some of the issues I let stagnate over the years after I stopped using this project.

**Comment by cuspymd** [comment]
I created [PR](https://github.com/melpa/melpa/pull/7969) on Melpa. 
Thanks for good package. I will try to maintain it well.

**Comment by cuspymd** [comment]
Completed takeover
